apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-php-ingress
  annotations:
    # 1. On garde l'ingress class
    kubernetes.io/ingress.class: "nginx"
    
    # 2. AJOUT : La redirection HTTPS automatique (remplace le FrontendConfig)
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    
    # 3. Cert-manager (si vous l'avez install√©)
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - test.christien.pro
    secretName: test-christien-tls
  rules:
    - host: test.christien.pro
      http:
        paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: api-service
              port:
                number: 80
  defaultBackend:
    service:
      name: frontend-service
      port:
        number: 80